//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgingInHome.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AgingInHomeContext : DbContext
    {
        public AgingInHomeContext()
            : base("name=AgingInHomeContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Attachment> Attachments { get; set; }
        public virtual DbSet<CategoryService> CategoryServices { get; set; }
        public virtual DbSet<ContactU> ContactUs { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<FavoriteDetail> FavoriteDetails { get; set; }
        public virtual DbSet<HourOfOperation> HourOfOperations { get; set; }
        public virtual DbSet<Inbox> Inboxes { get; set; }
        public virtual DbSet<ListingAboutU> ListingAboutUs { get; set; }
        public virtual DbSet<ListingArticle> ListingArticles { get; set; }
        public virtual DbSet<ListingBlog> ListingBlogs { get; set; }
        public virtual DbSet<ProviderCategory> ProviderCategories { get; set; }
        public virtual DbSet<RatingTable> RatingTables { get; set; }
        public virtual DbSet<RequiedListing> RequiedListings { get; set; }
        public virtual DbSet<ServiceArea> ServiceAreas { get; set; }
        public virtual DbSet<ServiceDetail> ServiceDetails { get; set; }
        public virtual DbSet<ServicePriceType> ServicePriceTypes { get; set; }
        public virtual DbSet<ServiceRequest> ServiceRequests { get; set; }
        public virtual DbSet<ServiceRequestCategory> ServiceRequestCategories { get; set; }
        public virtual DbSet<ServiceRequestDetail> ServiceRequestDetails { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<MasterProviderCategoryService> MasterProviderCategoryServices { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ProviderImageGalary> ProviderImageGalaries { get; set; }
        public virtual DbSet<ProviderTeam> ProviderTeams { get; set; }
        public virtual DbSet<ProviderVideo> ProviderVideos { get; set; }
        public virtual DbSet<ProviderListing> ProviderListings { get; set; }
        public virtual DbSet<Analytic> Analytics { get; set; }
        public virtual DbSet<GoogleUser> GoogleUsers { get; set; }
        public virtual DbSet<AdwordBuget> AdwordBugets { get; set; }
        public virtual DbSet<AnalyticsStat> AnalyticsStats { get; set; }
        public virtual DbSet<Markup> Markups { get; set; }
        public virtual DbSet<ListingBlogComment> ListingBlogComments { get; set; }
        public virtual DbSet<ConsumerProfile> ConsumerProfiles { get; set; }
        public virtual DbSet<UsState> UsStates { get; set; }
    
        public virtual ObjectResult<ssp_GetProviderBlogData_Result> ssp_GetProviderBlogData(Nullable<int> pageNumber, Nullable<int> pageSize, string userId)
        {
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ssp_GetProviderBlogData_Result>("ssp_GetProviderBlogData", pageNumberParameter, pageSizeParameter, userIdParameter);
        }
    
        public virtual ObjectResult<ssp_GetProviderNewsData_Result> ssp_GetProviderNewsData(Nullable<int> pageNumber, Nullable<int> pageSize, string userId)
        {
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ssp_GetProviderNewsData_Result>("ssp_GetProviderNewsData", pageNumberParameter, pageSizeParameter, userIdParameter);
        }
    
        public virtual ObjectResult<ssp_GetProviderPhotosData_Result> ssp_GetProviderPhotosData(Nullable<int> pageNumber, Nullable<int> pageSize, string userId)
        {
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ssp_GetProviderPhotosData_Result>("ssp_GetProviderPhotosData", pageNumberParameter, pageSizeParameter, userIdParameter);
        }
    
        public virtual ObjectResult<ssp_GetProviderVideosData_Result> ssp_GetProviderVideosData(Nullable<int> pageNumber, Nullable<int> pageSize, string userId)
        {
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ssp_GetProviderVideosData_Result>("ssp_GetProviderVideosData", pageNumberParameter, pageSizeParameter, userIdParameter);
        }
    
        public virtual ObjectResult<ssp_GetProviderTeamData_Result> ssp_GetProviderTeamData(Nullable<int> pageNumber, Nullable<int> pageSize, string userId)
        {
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ssp_GetProviderTeamData_Result>("ssp_GetProviderTeamData", pageNumberParameter, pageSizeParameter, userIdParameter);
        }
    
        public virtual ObjectResult<ssp_GetProviderListAnalytic_Result> ssp_GetProviderListAnalytic()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ssp_GetProviderListAnalytic_Result>("ssp_GetProviderListAnalytic");
        }
    
        public virtual ObjectResult<ssp_GetBlogNewsDetails_Result> ssp_GetBlogNewsDetails(Nullable<int> blogNewsId, Nullable<bool> isBlog)
        {
            var blogNewsIdParameter = blogNewsId.HasValue ?
                new ObjectParameter("BlogNewsId", blogNewsId) :
                new ObjectParameter("BlogNewsId", typeof(int));
    
            var isBlogParameter = isBlog.HasValue ?
                new ObjectParameter("IsBlog", isBlog) :
                new ObjectParameter("IsBlog", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ssp_GetBlogNewsDetails_Result>("ssp_GetBlogNewsDetails", blogNewsIdParameter, isBlogParameter);
        }
    
        public virtual ObjectResult<usp_GetAnalyticsListing_Result> usp_GetAnalyticsListing(Nullable<int> pageNumber, Nullable<int> pageSize, ObjectParameter totalRecords)
        {
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetAnalyticsListing_Result>("usp_GetAnalyticsListing", pageNumberParameter, pageSizeParameter, totalRecords);
        }
    
        public virtual ObjectResult<usp_GetMarkups_Result> usp_GetMarkups(Nullable<int> pageNumber, Nullable<int> pageSize, ObjectParameter totalRecords)
        {
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetMarkups_Result>("usp_GetMarkups", pageNumberParameter, pageSizeParameter, totalRecords);
        }
    
        public virtual ObjectResult<usp_GetProviderListingRequest_Result> usp_GetProviderListingRequest(Nullable<int> pageNumber, Nullable<int> pageSize, ObjectParameter totalRecords)
        {
            var pageNumberParameter = pageNumber.HasValue ?
                new ObjectParameter("PageNumber", pageNumber) :
                new ObjectParameter("PageNumber", typeof(int));
    
            var pageSizeParameter = pageSize.HasValue ?
                new ObjectParameter("PageSize", pageSize) :
                new ObjectParameter("PageSize", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetProviderListingRequest_Result>("usp_GetProviderListingRequest", pageNumberParameter, pageSizeParameter, totalRecords);
        }
    }
}
