//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgingInHome.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Analytic
    {
        public int Id { get; set; }
        public int ProviderListingId { get; set; }
        public string ProfileID { get; set; }
        public string ViewID { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
