//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgingInHome.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AppointmentId { get; set; }
        public string ProviderId { get; set; }
        public string ConsumerId { get; set; }
        public System.DateTime ServiceDate { get; set; }
        public string BestTime { get; set; }
        public Nullable<bool> IsCancel { get; set; }
        public Nullable<System.DateTime> IsAlterTime { get; set; }
        public Nullable<bool> IsAlterOffer { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> ServiceRequestDetailsId { get; set; }
        public Nullable<bool> IsProviderCancel { get; set; }
        public Nullable<bool> IsProviderAccept { get; set; }
        public Nullable<bool> IsConsumerAccept { get; set; }
        public Nullable<int> AppointmentSendBy { get; set; }
        public Nullable<bool> IsRatingDisable { get; set; }
        public Nullable<int> ContactUsid { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual ServiceRequestDetail ServiceRequestDetail { get; set; }
    }
}
