//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgingInHome.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int AttachmentId { get; set; }
        public int InboxMessageId { get; set; }
        public string ResourcePath { get; set; }
        public string CreatedBy { get; set; }
        public string CreatedDate { get; set; }
    
        public virtual Inbox Inbox { get; set; }
    }
}
