//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgingInHome.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsumerProfile
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Zipcode { get; set; }
        public Nullable<int> StateId { get; set; }
        public string Gender { get; set; }
        public string Relation { get; set; }
        public Nullable<int> Age { get; set; }
        public string TypeOfMedicalInsurance { get; set; }
        public string PrimaryPhone { get; set; }
        public string AlterPhone { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual UsState UsState { get; set; }
    }
}
