//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgingInHome.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FavoriteDetail
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public int ProviderListingId { get; set; }
    
        public virtual ProviderListing ProviderListing { get; set; }
    }
}
