//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgingInHome.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HourOfOperation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HourOfOperation()
        {
            this.ProviderListings = new HashSet<ProviderListing>();
        }
    
        public int HourOfOperationId { get; set; }
        public string MonStart { get; set; }
        public string MonEnd { get; set; }
        public string TueStart { get; set; }
        public string TueEnd { get; set; }
        public string WedStart { get; set; }
        public string WedEnd { get; set; }
        public string ThuStart { get; set; }
        public string ThuEnd { get; set; }
        public string FriStart { get; set; }
        public string FriEnd { get; set; }
        public string SatStart { get; set; }
        public string SatEnd { get; set; }
        public string SunStart { get; set; }
        public string SunEnd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderListing> ProviderListings { get; set; }
    }
}
