//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgingInHome.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inbox
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inbox()
        {
            this.Attachments = new HashSet<Attachment>();
        }
    
        public int Id { get; set; }
        public string SenderId { get; set; }
        public string RecipientId { get; set; }
        public string Subject { get; set; }
        public string MessageBody { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<int> ServiceRequestDetailsId { get; set; }
        public Nullable<bool> IsArchive { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public Nullable<bool> IsStarred { get; set; }
        public Nullable<bool> IsProviderArchive { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ConversationId { get; set; }
        public Nullable<int> ContactUsId { get; set; }
        public Nullable<bool> isAdminArchive { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual ContactU ContactU { get; set; }
        public virtual ServiceRequestDetail ServiceRequestDetail { get; set; }
    }
}
