//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgingInHome.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProviderListing
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProviderListing()
        {
            this.FavoriteDetails = new HashSet<FavoriteDetail>();
            this.ListingAboutUs = new HashSet<ListingAboutU>();
            this.ListingArticles = new HashSet<ListingArticle>();
            this.ListingBlogs = new HashSet<ListingBlog>();
            this.ProviderImageGalaries = new HashSet<ProviderImageGalary>();
            this.ProviderTeams = new HashSet<ProviderTeam>();
            this.ProviderVideos = new HashSet<ProviderVideo>();
            this.RatingTables = new HashSet<RatingTable>();
            this.ServiceAreas = new HashSet<ServiceArea>();
            this.ServiceDetails = new HashSet<ServiceDetail>();
            this.ServiceRequestDetails = new HashSet<ServiceRequestDetail>();
        }
    
        public int ProviderListingId { get; set; }
        public int CategoryId { get; set; }
        public string ProviderCategory { get; set; }
        public Nullable<int> CategoryServiceId { get; set; }
        public int ServicesAreaId { get; set; }
        public string Experience { get; set; }
        public string ProviderContactNumber { get; set; }
        public int HourOfOperationId { get; set; }
        public string ServiceDescription { get; set; }
        public string Logo { get; set; }
        public string PrimaryEmail { get; set; }
        public string CommunicationEmail { get; set; }
        public string Password { get; set; }
        public string GoogleURL { get; set; }
        public string FacebookURL { get; set; }
        public string TwitterURL { get; set; }
        public string WebsiteURL { get; set; }
        public string PinterestURL { get; set; }
        public System.DateTime ListingDate { get; set; }
        public Nullable<decimal> ServicePrice { get; set; }
        public string ServicePriceType { get; set; }
        public string WhoWeAre { get; set; }
        public string WhyWeDo { get; set; }
        public string WhatWeDo { get; set; }
        public string WhenWeDo { get; set; }
        public int IsApproved { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string UserId { get; set; }
        public string ProviderAddress { get; set; }
        public string CompanyName { get; set; }
        public Nullable<bool> IsBlogShow { get; set; }
        public Nullable<bool> IsNewsShow { get; set; }
        public Nullable<bool> IsAboutUsShow { get; set; }
        public Nullable<bool> IsPhotosShow { get; set; }
        public Nullable<bool> IsVideoShow { get; set; }
        public string City { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> Zipcode { get; set; }
        public Nullable<bool> IsTeamShow { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual CategoryService CategoryService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoriteDetail> FavoriteDetails { get; set; }
        public virtual HourOfOperation HourOfOperation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListingAboutU> ListingAboutUs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListingArticle> ListingArticles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ListingBlog> ListingBlogs { get; set; }
        public virtual ProviderCategory ProviderCategory1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderImageGalary> ProviderImageGalaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderTeam> ProviderTeams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProviderVideo> ProviderVideos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RatingTable> RatingTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceArea> ServiceAreas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceDetail> ServiceDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestDetail> ServiceRequestDetails { get; set; }
        public virtual UsState UsState { get; set; }
    }
}
