//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgingInHome.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RatingTable
    {
        public int RatingId { get; set; }
        public int ProviderListingId { get; set; }
        public string UserId { get; set; }
        public Nullable<int> Speedpoint { get; set; }
        public Nullable<int> QualityPoint { get; set; }
        public Nullable<int> ReliabilityPoint { get; set; }
        public string Comments { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual ProviderListing ProviderListing { get; set; }
    }
}
