//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgingInHome.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequestCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceRequestCategory()
        {
            this.ServiceRequestDetails = new HashSet<ServiceRequestDetail>();
        }
    
        public int Id { get; set; }
        public int ProviderCategoryId { get; set; }
        public int ServiceRequestId { get; set; }
        public Nullable<bool> Iswait7days { get; set; }
        public Nullable<System.DateTime> LastUpdation { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public string BestTime { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ProviderCategory ProviderCategory { get; set; }
        public virtual ServiceRequest ServiceRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestDetail> ServiceRequestDetails { get; set; }
    }
}
