//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgingInHome.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceRequest()
        {
            this.ServiceRequestCategories = new HashSet<ServiceRequestCategory>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public Nullable<int> StateId { get; set; }
        public int ZipCode { get; set; }
        public string Email { get; set; }
        public string PrimaryPhone { get; set; }
        public string AlternatePhone { get; set; }
        public Nullable<System.DateTime> ServiceDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> IsDirectContact { get; set; }
        public string ResultUrl { get; set; }
        public string Relation { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string TypeOfMedicalInsurence { get; set; }
        public string BestTime { get; set; }
        public Nullable<int> RequestStatus { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public Nullable<System.DateTime> LastUpdation { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceRequestCategory> ServiceRequestCategories { get; set; }
    }
}
