//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgingInHome.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceRequestDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ServiceRequestDetail()
        {
            this.Appointments = new HashSet<Appointment>();
            this.Inboxes = new HashSet<Inbox>();
        }
    
        public int Id { get; set; }
        public int ProviderListingId { get; set; }
        public Nullable<bool> IsProviderInvite { get; set; }
        public Nullable<bool> IsConsumerAcceptInvite { get; set; }
        public Nullable<System.DateTime> EmailDateTime { get; set; }
        public Nullable<bool> Mailrespose { get; set; }
        public Nullable<bool> IsWaitMore7Days { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> ServiceRequestCatId { get; set; }
        public Nullable<System.DateTime> LastUpdation { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Inbox> Inboxes { get; set; }
        public virtual ServiceRequestCategory ServiceRequestCategory { get; set; }
        public virtual ProviderListing ProviderListing { get; set; }
    }
}
