//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgingInHome.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceArea
    {
        public int Id { get; set; }
        public int ProviderListingId { get; set; }
        public string City { get; set; }
        public int StateId { get; set; }
        public string ZipCode { get; set; }
        public int ServiceRadius { get; set; }
    
        public virtual ProviderListing ProviderListing { get; set; }
        public virtual UsState UsState { get; set; }
    }
}
